# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python

# Run jobs on container-based infrastructure, can be overridden per job
sudo: false

matrix:
  include:
    - python: 3.6
    - numpy: 1.15.4
    - scipy: 1.1.0
    - matplotlib: 3.0.1
before_install:
  - uname -a
  - free -m
  - df -h
  - ulimit -a
  - python -V
  - pip install --upgrade pip setuptools
  - pip install pytest pytest-cov
  - pip install numpy
  - pip install codecov
  - pip install -e .

script:
  - py.test -v --cov=./

# after_success:
#   - ./tools/travis-upload-wheel.sh

notifications:
    email: false

after_success:
  - codecov
